#!/bin/bash

XDG_CONFIG_HOME="${HOME}/.config"

BINDIR="/usr/local/bin"
HOMEBREW_HOME="/usr/local/Homebrew"
HOMEBREW_CORE_HOME="${HOMEBREW_HOME}/Library/Taps/homebrew/homebrew-core"
HOMEBREW_TARBALL="https://github.com/Homebrew/brew/tarball/master"
HOMEBREW_CORE_TARBALL="https://github.com/Homebrew/homebrew-core/tarball/master"
PROJECTS_HOME="${HOME}/Projects"
DOTFILES_REPO="https://github.com/pvande/dotfiles"
DOTFILES_HOME="${PROJECTS_HOME}/dotfiles"

abort() {
  echo '‼️ ' "$@" "See $LOGFILE for details."
  exit 1
}

announce() {
  echo '📢 ' "$@"
}

warn() {
  echo '⛔️ ' "$@"
}

info() {
  echo '💡 ' "$@"
}

good() {
  echo '✅ ' "$@"
}

installed() {
  $BINDIR/brew ls $@ &>/dev/null
}

postinstall() {
  local var="postinstall_$1"
  [ "${!var}" != '-' ] && {
    echo "❗️ " "$1 Caveats"
    {
      if [ -z "${!var}" ]; then
        brew info $1 | sed '/==> Caveats/,/==>/!d;//d'
      else
        echo -ne "${!var}"
      fi
    } | sed -e 's/^/   /'
  }
}

ensure-line-in-file() {
  local file="$1"
  shift
  local line="$*"

  grep -qs "$line" "$file" || echo "$line" >> "$file"
}

global-gitignore() {
  ensure-line-in-file "${XDG_CONFIG_HOME}/git/ignore" $*
}

TMPDIR=$(mktemp -d)

announce "Configuring $(hostname -s)"

sudo_permissions="[ '$(stat -f '%u:%Sg:%p' /usr/local 2>/dev/null)' != '501:staff:40755' ]"
sudo_xcode_tools="[ ! -x $('/usr/bin/xcode-select' -print-path 2>/dev/null || echo '/dev/null')/usr/bin/git ]"
sudo_etc_shells='grep -q /usr/local/bin/zsh /etc/shells'

if ($sudo_permissions) || ($sudo_xcode_tools) || !($sudo_etc_shells); then
  warn "Super-user privileges are required for the following changes:"
  $sudo_permissions   && warn "  Fixing permissions on /usr/local"
  $sudo_xcode_tools   && warn "  Installing the Xcode Command Line Tools"
  !($sudo_etc_shells) && warn "  Adding zsh to /etc/shells"
  sudo -k
  sudo -v

  if $sudo_permissions; then
    info "Fixing permissions on /usr/local..."
    sudo mkdir -p /usr/local/{bin,etc,Frameworks,include,lib,sbin,share,var} &&
    sudo chown -R 501:staff /usr/local/* &&
    sudo chmod -R +a "group:staff allow list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" /usr/local
  fi

  if $sudo_xcode_tools; then
    info "Installing the Xcode Command Line Tools..."
    sudo touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    sudo /usr/sbin/softwareupdate -i "$(softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | tail -n1)" &>/dev/null
    sudo rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    sudo '/usr/bin/xcode-select' --switch /Library/Developer/CommandLineTools &>/dev/null
  fi

  if !($sudo_etc_shells); then
    info "Adding zsh to /etc/shells..."
    sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells"
  fi

  warn "Releasing super-user privileges."
  sudo -k
fi

good "Permissions on /usr/local are correct..."
good "Xcode Command Line Tools are present..."
good "zsh is in /etc/shells..."

LOGFILE="${TMPDIR}/homebrew.log"
if [ ! -x $BINDIR/brew ]; then
  info "Installing Homebrew..."
  {
    echo "Downloading and unpacking Homebrew..." &&
    mkdir -p $BINDIR &&
    mkdir -p $HOMEBREW_HOME &&
    cd $HOMEBREW_HOME &&
    /usr/bin/curl -fsSL $HOMEBREW_TARBALL | /usr/bin/tar xz -m --strip 1 &&
    ln -sf ${HOMEBREW_HOME}/bin/brew $BINDIR/brew &&

    echo "Downloading and unpacking Homebrew Core..." &&
    mkdir -p $HOMEBREW_CORE_HOME &&
    cd $HOMEBREW_CORE_HOME &&
    /usr/bin/curl -fsSL $HOMEBREW_CORE_TARBALL | /usr/bin/tar xz -m --strip 1 &&

    echo 'Running `brew update --force`...' &&
    brew update --force
  } &>$LOGFILE || abort "Could not install Homebrew!"
else
  {
    $BINDIR/brew update
  } &>$LOGFILE || abort "Could not update Homebrew!"
fi
good "Homebrew is up-to-date..."

PATH="$BINDIR:$PATH"

LOGFILE="${TMPDIR}/git.log"
if !(installed git); then
  info "Installing Git from Homebrew..."
  {
    $BINDIR/brew install git
  } &>$LOGFILE || abort "Could not install Git!"
fi
good "Git is present..."
export postinstall_git="-"

LOGFILE="${TMPDIR}/dotfiles.log"
if [ ! -d $PROJECTS_HOME/dotfiles ]; then
  info "Cloning $DOTFILES_REPO to $DOTFILES_HOME..."
  {
    git clone $DOTFILES_REPO $DOTFILES_HOME
  } &>$LOGFILE || abort "Could not clone $DOTFILES_REPO!"
elif !(cd $DOTFILES_HOME && git fetch -q && git status | grep -q 'up-to-date'); then
  info "Updating $DOTFILES_HOME..."
  {
    cd $DOTFILES_HOME &&
    git merge origin/master
  } &>$LOGFILE || abort "Could not update $DOTFILES_REPO!"
fi
good "dotfiles repository is up-to-date..."

for sh in $DOTFILES_HOME/config/*.sh ; do
  [ -r "${sh}" ] && source "${sh}"
done
unset sh

for cmd in $(brew list); do
  if (brew info $cmd | grep -q Caveats); then
    postinstall $cmd
  fi
done

rm -r $TMPDIR
announce "All set!"
