#!/bin/bash

BINDIR="/usr/local/bin"
HOMEBREW_HOME="/usr/local/Homebrew"
HOMEBREW_CORE_HOME="${HOMEBREW_HOME}/Library/Taps/homebrew/homebrew-core"
HOMEBREW_TARBALL="https://github.com/Homebrew/brew/tarball/master"
HOMEBREW_CORE_TARBALL="https://github.com/Homebrew/homebrew-core/tarball/master"
PROJECTS_HOME="${HOME}/Projects"
DOTFILES_REPO="https://github.com/pvande/dotfiles"
DOTFILES_HOME="${PROJECTS_HOME}/dotfiles"

abort() {
  echo '‼️ ' "$@" "See $LOGFILE for details."
  exit 1
}

announce() {
  echo '📢 ' "$@"
}

warn() {
  echo '⛔️ ' "$@"
}

info() {
  echo '💡 ' "$@"
}

good() {
  echo '✅ ' "$@"
}

TMPDIR=$(mktemp -d)

announce "Configuring $(hostname -s)"

sudo_permissions="[ '$(stat -f '%Su:%p' /usr/local 2>&1)' != '$(whoami):40775' ]"
sudo_xcode_tools="[ ! -x $('/usr/bin/xcode-select' -print-path 2>/dev/null || echo '/dev/null')/usr/bin/git ]"

if $sudo_permissions || $sudo_xcode_tools; then
  warn "Super-user privileges are required for the following changes:"
  $sudo_permissions && warn "  Fixing permissions on /usr/local"
  $sudo_xcode_tools && warn "  Installing the Xcode Command Line Tools"
  sudo -k
  sudo -v

  if $sudo_permissions; then
    info "Fixing permissions on /usr/local..."
    sudo mkdir -p /usr/local &&
    sudo chown -R $(whoami):staff /usr/local &&
    chmod -R 0775 /usr/local
  fi

  if $sudo_xcode_tools; then
    info "Installing the Xcode Command Line Tools..."
    sudo touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    sudo /usr/sbin/softwareupdate -i "$(softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\\*/ {print $2}' | sed 's/^ *//' | tail -n1)" &>/dev/null
    sudo rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    sudo '/usr/bin/xcode-select' --switch /Library/Developer/CommandLineTools &>/dev/null
  fi

  warn "Releasing super-user privileges."
  sudo -k
fi
good "Permissions on /usr/local are correct..."
good "Xcode Command Line Tools are present..."

LOGFILE="${TMPDIR}/homebrew.log"
if [ ! -x $BINDIR/brew ]; then
  info "Installing Homebrew..."
  {
    echo "Downloading and unpacking Homebrew..." &&
    mkdir -p $BINDIR &&
    mkdir -p $HOMEBREW_HOME &&
    cd $HOMEBREW_HOME &&
    /usr/bin/curl -fsSL $HOMEBREW_TARBALL | /usr/bin/tar xz -m --strip 1 &&
    ln -sf ${HOMEBREW_HOME}/bin/brew $BINDIR/brew &&

    echo "Downloading and unpacking Homebrew Core..." &&
    mkdir -p $HOMEBREW_CORE_HOME &&
    cd $HOMEBREW_CORE_HOME &&
    /usr/bin/curl -fsSL $HOMEBREW_CORE_TARBALL | /usr/bin/tar xz -m --strip 1 &&

    echo 'Running `brew update --force`...' &&
    brew update --force
  } &>$LOGFILE || abort "Could not install Homebrew!"
else
  {
    $BINDIR/brew update
  } &>$LOGFILE || abort "Could not update Homebrew!"
fi
good "Homebrew is up-to-date..."

PATH="$BINDIR:$PATH"

LOGFILE="${TMPDIR}/git.log"
if !($BINDIR/brew ls git &>/dev/null); then
  info "Installing Git from Homebrew..."
  {
    $BINDIR/brew install git
  } &>$LOGFILE || abort "Could not install Git!"
fi
good "Git is present..."

LOGFILE="${TMPDIR}/dotfiles.log"
if [ ! -d $PROJECTS_HOME/dotfiles ]; then
  info "Cloning $DOTFILES_REPO to $DOTFILES_HOME..."
  {
    git clone $DOTFILES_REPO $DOTFILES_HOME
  } &>$LOGFILE || abort "Could not clone $DOTFILES_REPO!"
elif !(cd $DOTFILES_HOME && git fetch -q && git status | grep -q 'up-to-date'); then
  info "Updating $DOTFILES_HOME..."
  {
    cd $DOTFILES_HOME &&
    git merge origin/master
  } &>$LOGFILE || abort "Could not update $DOTFILES_REPO!"
fi
good "$DOTFILES_HOME is up-to-date..."

for sh in $DOTFILES_HOME/config/*.sh ; do
  [ -r "${sh}" ] && source "${sh}"
done
unset sh

rm -r $TMPDIR
announce "All set!"
